In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np

import pathlib
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.datasets import load_diabetes

In [4]:
df = pd.read_csv('C:/Users/frado/AI_STUDY_DATA/diabetes.csv', index_col=0)
X = df.drop('Outcome', axis=1)  # 특성 변수들
y = df['Outcome']  # 목표 변수


In [5]:
# train & test

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((576, 7), (192, 7), (576,), (192,))

In [6]:
# SVM

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(X_train, y_train)

pred_svm = clf_svm.predict(X_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
0.78125
[[119  11]
 [ 31  31]]


In [7]:
# LR

from sklearn.linear_model import LogisticRegression

clf_lr = LogisticRegression(random_state=0, max_iter=1000)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.7916666666666666
[[116  14]
 [ 26  36]]


In [8]:
# DT

from sklearn.tree import DecisionTreeClassifier

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.7447916666666666
[[103  27]
 [ 22  40]]


In [9]:
# RT

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd

print ("\n--- Random Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Random Forest ---
0.7760416666666666
[[114  16]
 [ 27  35]]


In [10]:
X = df.drop(['BMI', 'Outcome'], axis=1)

# 'BMI'를 레이블로 설정
y = df['BMI']

In [11]:
# train/test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=423)

In [12]:
# DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix

from sklearn.tree import DecisionTreeRegressor

clf_dt = DecisionTreeRegressor()
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print(clf_dt.score(X_train, y_train))

1.0


In [13]:
mse = np.sqrt(mean_squared_error(pred_dt, y_test))
print('평균제곱근오차', mse)

평균제곱근오차 7.9581413022773715


In [14]:
from sklearn.ensemble import RandomForestRegressor

rf_clf = RandomForestRegressor()
rf_clf.fit(X_train, y_train)

pred_rf = rf_clf.predict(X_test)

print(rf_clf.score(X_train, y_train))

0.9022986438070586


In [15]:
mse = np.sqrt(mean_squared_error(pred_rf, y_test))
print('평균제곱근오차', mse)

평균제곱근오차 6.207968393759916


In [16]:
from sklearn.linear_model import LinearRegression

clf_lr = LinearRegression()
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print(clf_lr.score(X_train, y_train))

0.21283409600548941


In [17]:
mse = np.sqrt(mean_squared_error(pred_lr, y_test))
print('평균제곱근오차', mse)

평균제곱근오차 6.677071661884182


In [18]:
from sklearn.svm import SVR

# SVR 모델 생성 및 학습
svr = SVR()
svr.fit(X_train, y_train)

# 예측
pred_svr = svr.predict(X_test)
print(pred_svr)

[32.71005309 34.1809798  32.75065468 30.75198207 32.0696898  33.42643376
 33.65963746 31.6058348  29.31062589 32.15928526 32.37795456 32.48403927
 31.77943345 30.62896451 29.31368117 28.17330309 31.51499684 31.31382656
 33.83551882 30.43705463 34.57022938 32.8916869  30.55552615 28.42587921
 28.64682557 29.3171697  33.96366905 32.82317131 30.3708397  29.26637964
 32.11371126 29.06502091 30.457392   30.90427575 34.40919183 31.18643579
 29.28908995 31.68118178 30.09202985 35.85374159 29.13261554 29.30117201
 29.91828144 31.50706458 30.3709363  31.94472049 36.12305692 35.5969818
 37.3397052  32.4093092  30.06713465 31.37839245 32.32982004 33.93214766
 33.37501902 35.10629214 31.04970743 35.76435718 30.33758018 30.81493838
 33.19153791 30.00942154 34.69548565 29.01204948 28.67647251 32.12846098
 34.31628772 35.99382387 34.21298726 29.79513166 30.26756844 33.89894446
 30.12039558 32.52700983 36.03623522 31.93068254 30.25677712 34.79735827
 31.05549036 31.38306606 30.12337654 30.59453577 35.

In [19]:
mse = np.sqrt(mean_squared_error(pred_svr, y_test))
print('SVR 평균제곱근오차:', mse)

SVR 평균제곱근오차: 7.116898296560277
