In [19]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np

import pathlib
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [20]:
df = pd.read_excel('C:/Users/frado/AI_STUDY_DATA/Raisin_Dataset.xlsx', index_col=0, engine='openpyxl')
X = df.drop('Class', axis=1)  # 특성 변수들
y = df['Class']  # 목표 변수


In [21]:
# train & test

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((675, 6), (225, 6), (675,), (225,))

In [22]:
# SVM

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(X_train, y_train)

pred_svm = clf_svm.predict(X_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
0.8133333333333334
[[ 83  32]
 [ 10 100]]


In [23]:
# LR

from sklearn.linear_model import LogisticRegression

clf_lr = LogisticRegression(random_state=0, max_iter=1000)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.8844444444444445
[[ 98  17]
 [  9 101]]


In [24]:
# DT

from sklearn.tree import DecisionTreeClassifier

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.7955555555555556
[[92 23]
 [23 87]]


In [25]:
# RT

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd

print ("\n--- Random Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Random Forest ---
0.8711111111111111
[[98 17]
 [12 98]]


In [26]:
X = df.drop(['Perimeter', 'Class'], axis=1)  #Perimeter'와 'Class' 열을 제외한 모든 열을 특성으로 사용
y = df['Perimeter']  # 'Perimeter' 열을 목표 변수로 사용


In [27]:
# train/test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=423)

In [28]:
# DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix

from sklearn.tree import DecisionTreeRegressor

clf_dt = DecisionTreeRegressor()
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print(clf_dt.score(X_train, y_train))

1.0


In [29]:
mse = np.sqrt(mean_squared_error(pred_dt, y_test))
print('평균제곱근오차', mse)

평균제곱근오차 43.140461102658605


In [30]:
from sklearn.ensemble import RandomForestRegressor

rf_clf = RandomForestRegressor()
rf_clf.fit(X_train, y_train)

pred_rf = rf_clf.predict(X_test)

print(rf_clf.score(X_train, y_train))

0.9984489896654595


In [31]:
mse = np.sqrt(mean_squared_error(pred_rf, y_test))
print('평균제곱근오차', mse)

평균제곱근오차 35.47424324578047


In [32]:
from sklearn.linear_model import LinearRegression

clf_lr = LinearRegression()
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print(clf_lr.score(X_train, y_train))

0.9879664542273404


In [33]:
mse = np.sqrt(mean_squared_error(pred_lr, y_test))
print('평균제곱근오차', mse)

평균제곱근오차 29.058940340153367


In [34]:
from sklearn.svm import SVR

# SVR 모델 생성 및 학습
svr = SVR()
svr.fit(X_train, y_train)

# 예측
pred_svr = svr.predict(X_test)
print(pred_svr)

[1076.59211635 1147.26412631 1263.7908251  1092.83942365 1018.25682471
 1312.45722198 1135.50287873 1057.83372953 1036.4021595  1132.50770743
 1034.24660694 1079.86045089 1309.67149421 1312.99660022 1088.12648491
 1011.9339965  1178.26210967 1050.54965892 1082.98716955 1295.68808802
 1036.22711432 1055.64362712 1294.46967087 1105.978489   1083.87167775
 1312.88206886 1038.06188648 1255.31465531 1028.42025624 1051.9851098
 1221.9342243  1131.7743927  1084.98717825 1047.75057796 1184.32077338
 1147.73425632 1058.16203119 1108.33110476 1119.26436027 1097.06263439
 1061.03412972 1310.41981476 1084.18436575 1310.01453425 1021.06204468
 1307.6509664  1096.90201936 1219.03457313 1139.83493122 1260.13875789
 1061.69468137 1201.17529015 1043.43604488 1081.16214479 1255.48382785
 1059.85642847 1029.94294848 1193.00124389 1101.29190293 1306.79195905
 1163.82271575 1259.1428383  1263.45891483 1049.68347943 1018.32005198
 1044.89964226 1307.50130722 1018.4811317  1300.99209733 1084.82917656
 1230.0

In [35]:
mse = np.sqrt(mean_squared_error(pred_svr, y_test))
print('SVR 평균제곱근오차:', mse)

SVR 평균제곱근오차: 185.52996271685382
