In [3]:
import numpy as np #헤더파일 불러오는 거랑 비슷한듯
import pandas as pd
import seaborn as sns #as는 너무 긴 것을 축약하는 거임 
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore') #프로그램 실행에 문제되지 않는 warning 은 다 무시 

In [28]:
df = pd.read_csv('C:/Users/frado/AI_STUDY_DATA/abalone/abalone.csv.csv', index_col=0)
df.columns =['Length','Diameter','Height','Whole weight','Shucked weight','Viscera weight','Shell weight','Rings']
df


Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
M                                                                            
M    0.350     0.265   0.090        0.2255          0.0995          0.0485   
F    0.530     0.420   0.135        0.6770          0.2565          0.1415   
M    0.440     0.365   0.125        0.5160          0.2155          0.1140   
I    0.330     0.255   0.080        0.2050          0.0895          0.0395   
I    0.425     0.300   0.095        0.3515          0.1410          0.0775   
..     ...       ...     ...           ...             ...             ...   
F    0.565     0.450   0.165        0.8870          0.3700          0.2390   
M    0.590     0.440   0.135        0.9660          0.4390          0.2145   
M    0.600     0.475   0.205        1.1760          0.5255          0.2875   
F    0.625     0.485   0.150        1.0945          0.5310          0.2610   
M    0.710     0.555   0.195        1.9485          0.9455          0.3765   

    Shell weight  Rings  
M                        
M         0.0700      7  
F         0.2100      9  
M         0.1550     10  
I         0.0550      7  
I         0.1200      8  
..           ...    ...  
F         0.2490     11  
M         0.2605     10  
M         0.3080      9  
F         0.2960     10  
M         0.4950     12  

[4176 rows x 8 columns]

In [59]:
df['Rings'].value_counts()

9     689
10    634
8     568
11    487
7     391
12    267
6     259
13    203
14    126
5     115
15    102
16     67
17     58
4      57
18     42
19     32
20     26
3      15
21     14
23      9
22      6
24      2
27      2
1       1
25      1
2       1
26      1
29      1
Name: Rings, dtype: int64

In [29]:
X = df.drop('Rings', axis=1)  # 특성 변수들
y = df['Rings']  # 목표 변수

In [30]:
# train & test

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3132, 7), (1044, 7), (3132,), (1044,))

In [31]:
# SVM

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(X_train, y_train)

pred_svm = clf_svm.predict(X_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
0.27298850574712646
[[ 0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 14  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 11 19  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  5 20 37  8  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2 12 45 31  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  2 33 60 42  7  2  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3 18 43 66 40  7  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1 14 26 57 53 13  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  4 13 29 38 30  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  5 10 13 23 12  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  7 17 14  8  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  5  5  6  7  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  3  8 10  4  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  4  2  7  5  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  5  3  4  0 

In [32]:
# LR

from sklearn.linear_model import LogisticRegression

clf_lr = LogisticRegression(random_state=0, max_iter=1000)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.2662835249042146
[[ 0  0  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2 16  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1 23 11  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 17 43 10  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  8 49 31  9  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3 32 54 49  7  2  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  2 17 34 78 41  5  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 16 15 67 51 15  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  5  6 38 38 28  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  4  8 13 25 13  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  6 15 15 10  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  5  4  7  7  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  1  8 12  4  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  4  0  6  7  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 

In [33]:
# DT

from sklearn.tree import DecisionTreeClassifier

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.20977011494252873
[[ 0  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  6  3  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1 16 10  4  0  3  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  8 18 23  6  3  8  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  3  5 13 27 22 16  7  1  2  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1 12 25 44 18 24  7  8  3  1  4  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  8  9 41 36 29 28 11  8  3  3  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  3  7 19 34 38 31 14  6  1  3  0  2  0  1  1  1  2  0  0  0]
 [ 0  0  1  1  2 12 22 29 21 10  5  2  3  2  1  1  0  1  0  1  0  0  1]
 [ 0  0  0  2  6  4 10 11 12  3  0  2  4  3  2  1  0  0  1  0  1  0  1]
 [ 0  0  0  1  0  5  4  4  8 10  3  3  3  3  0  0  1  1  0  0  1  0  0]
 [ 0  0  0  0  2  0  3  4  2  3  2  1  0  3  2  1  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  4  2  5  2  4  5  1  0  0  1  1  0  0  0  0  0  0]
 [ 0  0  0

In [34]:
# RT

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd

print ("\n--- Random Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Random Forest ---
0.2557471264367816
[[ 0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  8  6  4  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1 13 16  4  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1 10 23 26  8  2  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  3 18 38 26  9  1  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1 13 28 51 29 15  7  2  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3 13 45 49 34 24  4  4  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  6 20 59 37 26  6  5  2  0  1  1  0  0  0  0  0  0]
 [ 0  0  0  2  3  9 20 39 29  5  5  2  0  0  1  0  0  0  0  0  0]
 [ 0  0  0  1  4  5 11 20 12  8  1  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  6  7 10 11  4  6  0  1  0  1  0  0  0  0  0  0]
 [ 0  0  0  1  1  0  4  3  5  2  2  2  1  2  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  5  6  5  3  3  2  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  4  1  2  1  3  4  1  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  2  3  0  1

In [36]:
df_without_Rings = df.drop('Rings', axis=1)
print(df_without_Rings.columns)

Index(['Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
       'Viscera weight', 'Shell weight'],
      dtype='object')


In [48]:
X = df_without_Rings.drop('Diameter', axis=1)  # 'petal width (cm)' 열을 제외한 나머지 열
y = df_without_Rings['Diameter']  # 'petal width (cm)' 열
df_without_Rings

Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
M                                                                            
M    0.350     0.265   0.090        0.2255          0.0995          0.0485   
F    0.530     0.420   0.135        0.6770          0.2565          0.1415   
M    0.440     0.365   0.125        0.5160          0.2155          0.1140   
I    0.330     0.255   0.080        0.2050          0.0895          0.0395   
I    0.425     0.300   0.095        0.3515          0.1410          0.0775   
..     ...       ...     ...           ...             ...             ...   
F    0.565     0.450   0.165        0.8870          0.3700          0.2390   
M    0.590     0.440   0.135        0.9660          0.4390          0.2145   
M    0.600     0.475   0.205        1.1760          0.5255          0.2875   
F    0.625     0.485   0.150        1.0945          0.5310          0.2610   
M    0.710     0.555   0.195        1.9485          0.9455          0.3765   

    Shell weight  
M                 
M         0.0700  
F         0.2100  
M         0.1550  
I         0.0550  
I         0.1200  
..           ...  
F         0.2490  
M         0.2605  
M         0.3080  
F         0.2960  
M         0.4950  

[4176 rows x 7 columns]

In [49]:
# train/test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=423)

In [50]:
# DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix

from sklearn.tree import DecisionTreeRegressor

clf_dt = DecisionTreeRegressor()
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print(clf_dt.score(X_train, y_train))

1.0


In [51]:
mse = np.sqrt(mean_squared_error(pred_dt, y_test))
print('평균제곱근오차', mse)

평균제곱근오차 0.021564136006863063


In [52]:
from sklearn.ensemble import RandomForestRegressor

rf_clf = RandomForestRegressor()
rf_clf.fit(X_train, y_train)

pred_rf = rf_clf.predict(X_test)

print(rf_clf.score(X_train, y_train))

0.996775020937512


In [53]:
mse = np.sqrt(mean_squared_error(pred_rf, y_test))
print('평균제곱근오차', mse)

평균제곱근오차 0.01572084089725312


In [54]:
from sklearn.linear_model import LinearRegression

clf_lr = LinearRegression()
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print(clf_lr.score(X_train, y_train))

0.976448521812965


In [55]:
mse = np.sqrt(mean_squared_error(pred_lr, y_test))
print('평균제곱근오차', mse)

평균제곱근오차 0.015854209561703775


In [56]:
from sklearn.svm import SVR

# SVR 모델 생성 및 학습
svr = SVR()
svr.fit(X_train, y_train)

# 예측
pred_svr = svr.predict(X_test)
print(pred_svr)

[0.46075291 0.48340722 0.24201686 0.43292552 0.33864318 0.4401822
 0.41990146 0.44293488 0.52147943 0.24941811 0.40907651 0.36514351
 0.40835629 0.32092405 0.23265662 0.42453559 0.38281933 0.40745211
 0.24748295 0.17618076 0.47192967 0.21464735 0.45869538 0.35291338
 0.4414577  0.17851752 0.48700426 0.37938958 0.45019949 0.43000048
 0.42605793 0.27220344 0.43524427 0.27441263 0.37721367 0.48743138
 0.34036421 0.47677913 0.42292232 0.42725982 0.38482006 0.51033076
 0.51260478 0.18273723 0.24079935 0.51067614 0.17847878 0.36033422
 0.24373891 0.42659996 0.47200579 0.26915185 0.18170479 0.25394076
 0.43403986 0.40146788 0.47193474 0.45742036 0.44268098 0.25193169
 0.2224484  0.48157945 0.28562931 0.45140167 0.36465264 0.35542715
 0.3240576  0.19195166 0.53369128 0.46514422 0.46947472 0.52841035
 0.49784493 0.48483481 0.27462014 0.41504065 0.50738913 0.32007229
 0.42155035 0.50230649 0.51259883 0.39019681 0.49597595 0.51714962
 0.38150052 0.27783104 0.31030424 0.23523694 0.46339052 0.44636

In [57]:
mse = np.sqrt(mean_squared_error(pred_svr, y_test))
print('SVR 평균제곱근오차:', mse)

SVR 평균제곱근오차: 0.02292687187653674
